name: flutter_kurs
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_localizations: 
    sdk: flutter
  flutter:
    sdk: flutter

  adaptive_theme: ^2.3.0
  intl: ^0.17.0
  get: ^4.5.1
  provider: ^6.0.1

  #lesson 7
  font_awesome_flutter: ^8.4.0

  #lesson_8  
  geolocator: ^7.7.1

  animated_text_kit: ^4.2.1
  audioplayers: ^0.20.1

  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  cloud_firestore: ^3.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Cookie
      fonts:
        - asset: assets/fonts/Cookie-Regular.ttf
    - family: Spartan MB
      fonts:
        - asset: assets/fonts/SpartanMB-Black.otf

  assets:
    - assets/images/
    - assets/images/lesson_3/
    - assets/images/lesson_4/
    - assets/notes/
    - assets/images/weather/
    - assets/images/chat/
    - assets/images/load/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
